const propiedades = [
    {
        titulo: 'Andria House',
        descripcion: 'Un nuevo paraíso en el norte de la Ciudad de Mérida con 6 bellos modelos de vivienda, ubicadas en cerradas, con amplias avenidas y áreas de donación jardinadas y amenidades.',
        habitaciones: 2,
        estacionamiento: 1,
        wc: 2,
        calle: 'Calle López Cotilla 2185',
        lat: '20.673169996903',
        lng: '-103.38327998453',
        imagen: 'ni2srkgt46g1hmpaqvmh.jpg',
        publicado: 0,
        precioId: 3,
        categoriaId: 1,
        usuarioId: 2
    },
    {
        titulo: 'Casa Bella Vista',
        descripcion: 'Hermosa casa con vista panorámica al lago, ubicada en una zona tranquila y segura. Ideal para familias que buscan confort y tranquilidad.',
        habitaciones: 3,
        estacionamiento: 2,
        wc: 3,
        calle: 'Avenida de las Flores 123',
        lat: 19.4326,
        lng: -99.1332,
        imagen: 'casa_bella_vista.jpg',
        publicado: 1,
        precioId: 5,
        categoriaId: 3,
        usuarioId: 2
    },
    {
        titulo: 'Casa del Bosque',
        descripcion: 'Acogedora casa rodeada de árboles y naturaleza. Perfecta para los amantes de la vida al aire libre y la tranquilidad.',
        habitaciones: 2,
        estacionamiento: 1,
        wc: 1,
        calle: 'Calle Roble 456',
        lat: 25.6866,
        lng: -100.3161,
        imagen: 'casa_del_bosque.jpg',
        publicado: 1,
        precioId: 2,
        categoriaId: 2,
        usuarioId: 2
    },
    {
        titulo: 'Casa Tranquila',
        descripcion: 'Amplia casa ubicada en una zona residencial tranquila. Ideal para familias grandes que buscan comodidad y seguridad.',
        habitaciones: 4,
        estacionamiento: 2,
        wc: 3,
        calle: 'Calle Olivos 789',
        lat: 20.9671,
        lng: -89.6237,
        imagen: 'casa_tranquila.jpg',
        publicado: 1,
        precioId: 7,
        categoriaId: 4,
        usuarioId: 2
    },
    {
        titulo: 'Casa del Lago',
        descripcion: 'Encantadora casa junto al lago, con impresionantes vistas y acceso privado al agua. Perfecta para relajarse y disfrutar de la naturaleza.',
        habitaciones: 4,
        estacionamiento: 3,
        wc: 2,
        calle: 'Calle del Lago 123',
        lat: 19.4236,
        lng: -99.1644,
        imagen: 'casa_lago.jpg',
        publicado: 1,
        precioId: 6,
        categoriaId: 3,
        usuarioId: 2
    },
    {
        titulo: 'Casa Moderna',
        descripcion: 'Moderna casa de diseño minimalista con interiores elegantes y espacios abiertos. Perfecta para aquellos que buscan un estilo de vida contemporáneo.',
        habitaciones: 3,
        estacionamiento: 2,
        wc: 3,
        calle: 'Avenida del Sol 456',
        lat: 25.6866,
        lng: -100.3161,
        imagen: 'casa_moderna.jpg',
        publicado: 1,
        precioId: 4,
        categoriaId: 2,
        usuarioId: 2
    },
    {
        titulo: 'Casa de Campo',
        descripcion: 'Acogedora casa de campo rodeada de naturaleza y tranquilidad. Ideal para escapar del bullicio de la ciudad y disfrutar de la vida rural.',
        habitaciones: 2,
        estacionamiento: 1,
        wc: 1,
        calle: 'Camino Real 789',
        lat: 20.9671,
        lng: -89.6237,
        imagen: 'casa_campo.jpg',
        publicado: 1,
        precioId: 3,
        categoriaId: 4,
        usuarioId: 2
    },
    {
        titulo: 'Villa Vista Mar',
        descripcion: 'Espectacular villa con vistas al mar, piscina privada y acceso directo a la playa. Ideal para unas vacaciones de lujo en la costa.',
        habitaciones: 3,
        estacionamiento: 4,
        wc: 4,
        calle: 'Calle del Mar 10',
        lat: 21.1619,
        lng: -86.8515,
        imagen: 'villa_vista_mar.jpg',
        publicado: 1,
        precioId: 9,
        categoriaId: 5,
        usuarioId: 2
    },
    {
        titulo: 'Casa de Montaña',
        descripcion: 'Encantadora casa de montaña con vistas panorámicas y acceso a rutas de senderismo. Perfecta para los amantes de la naturaleza y el aire fresco.',
        habitaciones: 3,
        estacionamiento: 2,
        wc: 2,
        calle: 'Camino de la Montaña 22',
        lat: 36.1699,
        lng: -115.1398,
        imagen: 'casa_montana.jpg',
        publicado: 1,
        precioId: 5,
        categoriaId: 3,
        usuarioId: 2
    },
    {
        titulo: 'Casa Colonial',
        descripcion: 'Elegante casa colonial con detalles arquitectónicos históricos y jardines exuberantes. Perfecta para los amantes del encanto y la tradición.',
        habitaciones: 4,
        estacionamiento: 2,
        wc: 3,
        calle: 'Calle Colonial 789',
        lat: 25.6866,
        lng: -100.3161,
        imagen: 'casa_colonial.jpg',
        publicado: 1,
        precioId: 6,
        categoriaId: 4,
        usuarioId: 2
    },
    {
        titulo: 'Casa de Playa',
        descripcion: 'Acogedora casa de playa con acceso directo a la arena y vistas impresionantes al océano. Ideal para disfrutar del sol y la brisa marina.',
        habitaciones: 3,
        estacionamiento: 2,
        wc: 2,
        calle: 'Avenida del Mar 123',
        lat: 19.2736,
        lng: -99.1444,
        imagen: 'casa_playa.jpg',
        publicado: 1,
        precioId: 7,
        categoriaId: 5,
        usuarioId: 2
    },
    {
        titulo: 'Casa Rural',
        descripcion: 'Tranquila casa rural ubicada en un pueblo pintoresco. Perfecta para aquellos que buscan escapar del ritmo frenético de la ciudad y conectarse con la naturaleza.',
        habitaciones: 2,
        estacionamiento: 1,
        wc: 1,
        calle: 'Calle de la Paz 456',
        lat: 40.7128,
        lng: -74.0060,
        imagen: 'casa_rural.jpg',
        publicado: 1,
        precioId: 3,
        categoriaId: 4,
        usuarioId: 2
    },
    {
        titulo: 'Casa de Diseño',
        descripcion: 'Innovadora casa de diseño con tecnología inteligente y espacios versátiles. Perfecta para aquellos que valoran la funcionalidad y la estética contemporánea.',
        habitaciones: 4,
        estacionamiento: 3,
        wc: 3,
        calle: 'Avenida Innovación 789',
        lat: 37.7749,
        lng: -122.4194,
        imagen: 'casa_diseno.jpg',
        publicado: 1,
        precioId: 8,
        categoriaId: 2,
        usuarioId: 2
    },
    {
        titulo: 'Casa del Bosque II',
        descripcion: 'Amplia casa rodeada de bosques y naturaleza. Ideal para quienes buscan tranquilidad y aire fresco en un entorno natural.',
        habitaciones: 3,
        estacionamiento: 2,
        wc: 2,
        calle: 'Camino de los Pinos 10',
        lat: 19.4326,
        lng: -99.1332,
        imagen: 'casa_bosque_2.jpg',
        publicado: 1,
        precioId: 5,
        categoriaId: 3,
        usuarioId: 2
    }

]

export default propiedades